name: Build and Publish Docker image 

on:
  push:
    branches: [ tests ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checking out the repo
    - name: Build and Publish Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: waitingforstock-backend # Provide Docker image name
        image-tag: latest # Provide Docker image tag
